### ISSUE TITLE
Question about the Workspace Starter for Symphony CMS

### ISSUE THREAD

**Issue by bzerangue** [craigerskine/workspace-starter#1]
@craigerskine, my name is Brian Zerangue. I have worked with Symphony CMS for a long time. I have run across your sites, one in particular... <https://www.getsymphony.com/explore/showcase/view/112661/>. Great work! I was curious if you had a repo showing how you use this workspace starter?

Would love to see how you use that.

**Comment by craigerskine** [comment]
@bzerangue
Thanks! Every site is different, but I use this workspace repo as a starting point. All of my sites that use Symphony also require this [repo](https://github.com/craigerskine/website-starter-gulp) as a starting point as well. I use a gulp build system with TailwindCSS and an extractor that trims the CSS to only the required classes. The extractor looks through all my xsl files to determine the bare minimum CSS... it works really, really well.

All the assets are compressed and the file names are suffixed with a hash. The master.xsl is auto modified with the updated file names via a manifest that keeps track of the hashed file names.

All I need to do is run gulp on my project folder, make changes, and everything is auto built and compressed as I work. Simple and fun. Setting up the gulp project takes a little work, but when it's all set, it works like magic.

Everything is managed in a Sublime Text project with a package that detects changes and auto syncs the files up to the server.

I keep everything in a theme folder for portability.

This [repo and video series](https://github.com/reygoch/flowershop) was very helpful for me when I started with Symphony.

**Comment by craigerskine** [comment]
Thanks for pinging me about this though @bzerangue, this has motivated me to create a true Symphony CMS, Gulp builder kit repo... I'll update this thread when it goes live.

**Comment by bzerangue** [comment]
Ok! Thanks so much @craigerskine

**Comment by craigerskine** [comment]
@bzerangue,
OK. I've update the repo with a better representation of how I usually work with Symphony CMS. I hope this helps.

**Comment by bzerangue** [comment]
Wow! I will take a look. Thank you so much!!!
